// Generated by Haxe 4.3.7
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"?",
"F:\\HaxeToolkit\\haxe\\std/cpp/_std/Reflect.hx",
"F:\\HaxeToolkit\\haxe\\std/cpp/_std/Std.hx",
"F:\\HaxeToolkit\\haxe\\std/cpp/_std/Type.hx",
"F:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/Exception.hx",
"F:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/Log.hx",
"F:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/NativeStackTrace.hx",
"F:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/ds/ObjectMap.hx",
"F:\\HaxeToolkit\\haxe\\std/cpp/_std/haxe/ds/StringMap.hx",
"F:\\HaxeToolkit\\haxe\\std/haxe/ValueException.hx",
"F:\\HaxeToolkit\\haxe\\std/haxe/iterators/ArrayIterator.hx",
"Test.hx",
"llua/Convert.hx",
"llua/Lua.hx",
"llua/LuaCallback.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"F:\\V-Slice-Modchart-Stuff-Unfinished\\.haxelib\\linc_luajit\\?",
"F:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Reflect.hx",
"F:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Std.hx",
"F:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\Type.hx",
"F:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\Exception.hx",
"F:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\Log.hx",
"F:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\NativeStackTrace.hx",
"F:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\ds\\ObjectMap.hx",
"F:\\HaxeToolkit\\haxe\\std\\cpp\\_std\\haxe\\ds\\StringMap.hx",
"F:\\HaxeToolkit\\haxe\\std\\haxe\\ValueException.hx",
"F:\\HaxeToolkit\\haxe\\std\\haxe\\iterators\\ArrayIterator.hx",
"F:\\V-Slice-Modchart-Stuff-Unfinished\\.haxelib\\linc_luajit\\Test.hx",
"F:\\V-Slice-Modchart-Stuff-Unfinished\\.haxelib\\linc_luajit\\git\\llua\\Convert.hx",
"F:\\V-Slice-Modchart-Stuff-Unfinished\\.haxelib\\linc_luajit\\git\\llua\\Lua.hx",
"F:\\V-Slice-Modchart-Stuff-Unfinished\\.haxelib\\linc_luajit\\git\\llua\\LuaCallback.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Reflect",
"Std",
"Test",
"Type",
"haxe.Exception",
"haxe.Log",
"haxe.NativeStackTrace",
"haxe.ValueException",
"haxe.ds.ObjectMap",
"haxe.ds.StringMap",
"haxe.iterators.ArrayIterator",
"llua.Convert",
"llua.Lua_helper",
"llua.LuaCallback",
"llua.Macro",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
