// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_cc9afe4755847ade
#define INCLUDED_cc9afe4755847ade
#include "linc_lua.h"
#endif
#ifndef INCLUDED_Test
#include <Test.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_df13cafffbed243f_9_main,"Test","main",0x9c6c95b5,"Test.main","Test.hx",9,0x8afb218c)

void Test_obj::__construct() { }

Dynamic Test_obj::__CreateEmpty() { return new Test_obj; }

void *Test_obj::_hx_vtable = 0;

Dynamic Test_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Test_obj > _hx_result = new Test_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Test_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x0c25ea96;
}

void Test_obj::main(){
            	HX_STACKFRAME(&_hx_pos_df13cafffbed243f_9_main)
HXLINE(  11)		 cpp::Reference<lua_State> vm = luaL_newstate();
HXLINE(  12)		luaL_openlibs(vm);
HXLINE(  13)		 ::Dynamic _hx_tmp = ::haxe::Log_obj::trace;
HXDLIN(  13)		::String _hx_tmp1 = (HX_("Lua version: ",36,0b,c4,a9) + linc::lua::version());
HXDLIN(  13)		_hx_tmp(_hx_tmp1,::hx::SourceInfo(HX_("Test.hx",8c,21,fb,8a),13,HX_("Test",72,f4,d2,37),HX_("main",39,38,56,48)));
HXLINE(  14)		 ::Dynamic _hx_tmp2 = ::haxe::Log_obj::trace;
HXDLIN(  14)		::String _hx_tmp3 = (HX_("LuaJIT version: ",fb,95,09,43) + linc::lua::versionJIT());
HXDLIN(  14)		_hx_tmp2(_hx_tmp3,::hx::SourceInfo(HX_("Test.hx",8c,21,fb,8a),14,HX_("Test",72,f4,d2,37),HX_("main",39,38,56,48)));
HXLINE(  16)		luaL_dofile(vm,HX_("script.lua",d5,d9,c1,2c));
HXLINE(  18)		lua_getglobal(vm,HX_("foo",06,c7,4d,00));
HXLINE(  20)		lua_pushinteger(vm,1);
HXLINE(  21)		lua_pushnumber(vm,((Float)2.0));
HXLINE(  22)		lua_pushstring(vm,HX_("three",5e,54,90,0f));
HXLINE(  24)		lua_pcall(vm,3,0,1);
HXLINE(  26)		lua_close(vm);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(Test_obj,main,(void))


Test_obj::Test_obj()
{
}

bool Test_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"main") ) { outValue = main_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *Test_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *Test_obj_sStaticStorageInfo = 0;
#endif

::hx::Class Test_obj::__mClass;

static ::String Test_obj_sStaticFields[] = {
	HX_("main",39,38,56,48),
	::String(null())
};

void Test_obj::__register()
{
	Test_obj _hx_dummy;
	Test_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("Test",72,f4,d2,37);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Test_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Test_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< Test_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Test_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Test_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

